#!/usr/bin/env python3
"""Write docs/llm-calls.md: every prompt and a real response, verbatim.

Generated from the live prompts rather than written by hand, so it cannot drift
from what is actually sent. Responses come from the committed caches, so the
examples are real verdicts and no call is made to produce them.

    python pipeline/dump_llm_calls.py
"""
from __future__ import annotations

import hashlib
import json

from config import CACHE, DOCS, RAW
from jsonio import read_json
from promote_literature import (SCOPE_SYSTEM, categorise_system, clip, abstracts,
                                SCOPE_CACHE, CAT_CACHE)

SCOPE_MODEL = "zai-org/GLM-5.3-Flash"
CAT_MODEL = "deepseek-ai/DeepSeek-V4-Flash"
PARAMS = ("temperature 0.3 · top_p 0.9 · max_tokens 400 · "
          "response_format json_object · enable_thinking false")


def user_message(r: dict, ab: dict) -> str:
    a = ab.get(str(r.get("pmid") or "")) or ab.get(str(r.get("doi") or "")) or ""
    if not a:
        return (f"Tool name: {r['name']}\n"
                f"Paper title: {r.get('description','')}\n(no abstract available)")
    return (f"Tool name: {r['name']}\nPaper title: {r.get('description','')}\n\n"
            f"Abstract:\n{clip(a)}")


def fence(text: str, lang: str = "") -> str:
    return f"```{lang}\n{text}\n```"


def main() -> None:
    ab = abstracts()
    cands = {r["name"]: r for r in read_json(RAW / "literature_candidates.json")["list"]}
    scope = {x["name"]: x for x in read_json(RAW / "literature_scope.json")["list"]}
    cats = {x["name"]: x for x in read_json(RAW / "literature_categories.json")["list"]}
    scope_sha = hashlib.sha256(SCOPE_SYSTEM.encode()).hexdigest()[:12]
    cat_system = categorise_system()
    cat_sha = hashlib.sha256(cat_system.encode()).hexdigest()[:12]

    # one record that passed both calls, and one that the scope call rejected
    passed = next(n for n in ("REPTILE", "Deopen", "coda") if n in cats)
    rejected = "NextPBM"

    out = [
        "# The LLM calls, verbatim",
        "",
        f"Generated by `pipeline/dump_llm_calls.py` from the live prompts. Prompt hashes: "
        f"scope `{scope_sha}`, categorise `{cat_sha}`. Every verdict stored in "
        "`data/raw/literature_scope.json` and `data/raw/literature_categories.json` records "
        "the hash that produced it, so a judgment can always be traced to the exact "
        "instructions behind it.",
        "",
        "A candidate reaches these calls only after clearing `select_domain.classify()` — the "
        "same six-step filter a bio.tools record faces. The models adjudicate records a "
        "deterministic domain filter has already admitted; they are not deciding scope from "
        "scratch on arbitrary input.",
        "",
        "---",
        "",
        "## Call 1 — scope and is_software",
        "",
        f"**Model** `{SCOPE_MODEL}` · {PARAMS}",
        "",
        "Two independent booleans. A candidate proceeds only if both are true.",
        "",
        "### System message",
        "",
        fence(SCOPE_SYSTEM),
        "",
        f"### User message — {passed}",
        "",
        fence(user_message(cands[passed], ab)),
        "",
        "### Response",
        "",
        fence(json.dumps({k: scope[passed].get(k) for k in
                          ("in_scope", "is_software", "confidence", "reason")}, indent=2), "json"),
        "",
        f"### User message — {rejected}, which this call rejects",
        "",
        fence(user_message(cands[rejected], ab)),
        "",
        "### Response",
        "",
        fence(json.dumps({k: scope[rejected].get(k) for k in
                          ("in_scope", "is_software", "confidence", "reason")}, indent=2), "json"),
        "",
        "The abstract's closing clause — \"and our accompanying computational framework\" — is "
        "what pulled an earlier version of this prompt across the line. The paragraph beginning "
        "\"Ask what the paper ANNOUNCES\" was added to answer it, and names this record as one of "
        "its worked examples.",
        "",
        "---",
        "",
        "## Call 2 — categorisation",
        "",
        f"**Model** `{CAT_MODEL}` · {PARAMS}",
        "",
        "A different model family from call 1, on purpose: the two answer different questions and "
        "must not share a blind spot. Runs only on candidates where both booleans came back true.",
        "",
        "### System message",
        "",
        fence(cat_system),
        "",
        f"### User message — {passed}",
        "",
        "Identical to the user message in call 1.",
        "",
        "### Response",
        "",
        fence(json.dumps({"categories": cats[passed].get("categories"),
                          "confidence": cats[passed].get("cat_confidence")}, indent=2), "json"),
        "",
        "Keys outside the taxonomy are recorded in an `invented` field rather than dropped. "
        "Across 562 calls there were none.",
        "",
    ]
    path = DOCS / "llm-calls.md"
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"-> {path}  ({len('\n'.join(out))//1024} KB)")


if __name__ == "__main__":
    main()
